created simple api with new routes
onlydevs-csus/cybercheck pull request #3
Opened 2022-10-30 03:27 UTC by KeatonWakefield001

2022-10-30 22:06 UTC, mudk01 requested changes

2022-10-30 22:06 UTC, mudk01 commented on server/src/routes/Report.ts
> +
Can you pls separate this into controller & services, and same with Users.ts

2022-10-31 02:52 UTC, mudk01 reviewed
LGTM!

2022-11-01 19:48 UTC, mudk01 approved these changes

2022-11-01 20:41 UTC, rlom721 approved these changes

2022-11-03 19:18 UTC, merged