[OD-82] Establish connection to database from backend
onlydevs-csus/cybercheck pull request #8
Opened 2022-11-09 05:10 UTC by rlom721

Updated the following files:
        modified:   package-lock.json
        new file:   package.json
        modified:   server/package-lock.json
        modified:   server/package.json
        new file:   server/src/config/dbConfig.ts
        new file:   server/src/db/passwordDb.ts

2022-11-10 04:57 UTC, mudk01 requested changes

2022-11-10 04:57 UTC, mudk01 commented on package.json
> +}
could you pls delete this file

2022-11-10 04:57 UTC, mudk01 commented on server/src/config/dbConfig.ts
> +const passwordDb = {
change name from passwordDb

2022-11-10 04:57 UTC, mudk01 commented on server/src/config/dbConfig.ts
> +    password: process.env.DB_PASSWORD
could you add `ssl: true` after password

2022-11-10 04:57 UTC, mudk01 commented on server/src/config/dbConfig.ts
> +export default passwordDb;
change here too

2022-11-10 04:57 UTC, mudk01 commented on server/src/db/passwordDb.ts
> +const passwordDbConfig = passwordDb;
also change file name and everything w/password lol

2022-11-10 23:29 UTC, rlom721 commented on server/src/config/dbConfig.ts
> +const passwordDb = {
yes sir

2022-11-15 18:27 UTC, mudk01 approved these changes
LGTM!

2022-11-16 19:52 UTC, KeatonWakefield001 reviewed
passed all manual test

2022-11-16 19:56 UTC, KeatonWakefield001 approved these changes
aprroving

2022-11-19 19:25 UTC, merged